spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/total_account_dup
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  liquibase:
    enabled: false
    change-log: classpath:config/liquibase/master.xml
server:
  port: 8080



