spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/total_account_dup
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
server:
  port: 8080



