-- liquibase formatted sql

-- changeset Bakhromjon:1698824921450-1
CREATE TABLE "user_role" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, CONSTRAINT "user_role_pkey" PRIMARY KEY ("id"));

-- changeset Bakhromjon:1698824921450-2
INSERT INTO "user_role" ("id", "name") VALUES (1, 'ROLE_USER');

-- changeset Bakhromjon:1698824921450-3
CREATE TABLE "users" ("is_deleted" BOOLEAN, "id" BIGINT NOT NULL, "role_id" BIGINT NOT NULL, "firstname" VARCHAR(255) NOT NULL, "lastname" VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, "username" VARCHAR(20) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset Bakhromjon:1698824921450-4
INSERT INTO "users" ("is_deleted", "id", "role_id", "firstname", "lastname", "password", "username") VALUES (FALSE, 1, 1, 'Bahromjon', 'Xasanboyev', '$2a$12$fN8F12PeGom1VClzLs1vH.Un2Ff.DsFcyJMSNOLZ.eS5PmdIo8gku', 'xbakhromjon');

-- changeset Bakhromjon:1698824921450-5
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_key" UNIQUE ("role_id");

-- changeset Bakhromjon:1698824921450-6
CREATE SEQUENCE  IF NOT EXISTS "expense_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Bakhromjon:1698824921450-7
CREATE SEQUENCE  IF NOT EXISTS "groups_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Bakhromjon:1698824921450-8
CREATE SEQUENCE  IF NOT EXISTS "person_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Bakhromjon:1698824921450-9
CREATE SEQUENCE  IF NOT EXISTS "users_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Bakhromjon:1698824921450-10
CREATE TABLE "expense" ("amount" FLOAT4 NOT NULL, "is_deleted" BOOLEAN, "group_id" BIGINT NOT NULL, "id" BIGINT NOT NULL, "name" VARCHAR(255) NOT NULL, CONSTRAINT "expense_pkey" PRIMARY KEY ("id"));

-- changeset Bakhromjon:1698824921450-11
CREATE TABLE "groups" ("is_deleted" BOOLEAN, "id" BIGINT NOT NULL, "owner_id" BIGINT NOT NULL, "name" VARCHAR(255) NOT NULL, CONSTRAINT "groups_pkey" PRIMARY KEY ("id"));

-- changeset Bakhromjon:1698824921450-12
CREATE TABLE "person" ("given_money" FLOAT4, "is_deleted" BOOLEAN, "group_id" BIGINT NOT NULL, "id" BIGINT NOT NULL, "nickname" VARCHAR(20) NOT NULL, CONSTRAINT "person_pkey" PRIMARY KEY ("id"));

-- changeset Bakhromjon:1698824921450-13
CREATE TABLE "user_role_privileges" ("user_role_id" BIGINT NOT NULL, "privileges" VARCHAR(255));

-- changeset Bakhromjon:1698824921450-14
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'DELETE_ACCOUNT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'GET_ONE_ANNOUNCEMENT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'FILTER_SEEN_ANNOUNCEMENT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'FILTER_PUBLIC_ANNOUNCEMENT_WITH_COUNT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'DELETE_ANNOUNCEMENT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'FILTER_PUBLIC_ANNOUNCEMENT_WITH_DETAILED_INFORMATION');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'GET_ACCOUNT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'UPDATE_ACCOUNT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'CREATE_ANNOUNCEMENT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'UPDATE_ANNOUNCEMENT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'FILTER_PURCHASED_ANNOUNCEMENT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'PUBLIC_ANNOUNCEMENT_FILTERS');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'FILTER_PUBLIC_ANNOUNCEMENT_WITH_HEADER_INFORMATION');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'PURCHASE_ANNOUNCEMENT');
INSERT INTO "user_role_privileges" ("user_role_id", "privileges") VALUES (1, 'PARTIAL_UPDATE_ACCOUNT');

-- changeset Bakhromjon:1698824921450-15
ALTER TABLE "person" ADD CONSTRAINT "fkam66y2ciskmv6xthckvdf9a73" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Bakhromjon:1698824921450-16
ALTER TABLE "groups" ADD CONSTRAINT "fkke9gpecgx7u1oef8lsd9tax3c" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Bakhromjon:1698824921450-17
ALTER TABLE "user_role_privileges" ADD CONSTRAINT "fko5ulh7fpyh8gx264drtpuqds9" FOREIGN KEY ("user_role_id") REFERENCES "user_role" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Bakhromjon:1698824921450-18
ALTER TABLE "users" ADD CONSTRAINT "fkqjp6iwe2anthe5yx88fl0coan" FOREIGN KEY ("role_id") REFERENCES "user_role" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Bakhromjon:1698824921450-19
ALTER TABLE "expense" ADD CONSTRAINT "fkr6ejg7yi3hnjlsp2vly81q2x9" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

